In [43]:
import pandas as pd
import numpy as np

In [44]:
combinedFile= r'C:\Users\aakri\OneDrive\Documents\cache\Risk_Analysis_csv.csv'

In [45]:
data1=pd.read_csv(combinedFile)

### Assembling a Portfolio:

In [46]:
data1.head()

Date      Google        MSFT         CVX     Oracle         IBM  \
0  01-06-2021  125.316002  267.383179  105.300003  75.683174  130.263489   
1  01-05-2021  120.578003  248.332779  105.260002  73.372520  124.684944   
2  01-04-2021  120.505997  245.870911  103.980003  76.558250  126.319496   
3  01-03-2021  103.431503  232.173157  102.459999  67.931786  117.109634   
4  01-02-2021  101.843002  228.309021   85.989998  62.452332  103.138115   

    Starbucks    FVX   S&P500  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0  108.325027  0.873  2067.56         NaN          NaN          NaN   
1  110.481926  0.857  1994.99         NaN          NaN          NaN   
2  109.893280  0.788  2058.90         NaN          NaN          NaN   
3  105.444656  0.938  2104.50         NaN          NaN          NaN   
4  103.806145  0.776  2067.89         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  
0          NaN          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN          NaN

In [47]:
data=data1.drop(['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16'], axis=1)

In [48]:
#data['Date']= pd.to_datetime(data['Date'], format='%d-%b-%y')

In [49]:
data=data.sort_values(['Date'],ascending=[True])

In [50]:
data.head()

Date     Google        MSFT         CVX     Oracle         IBM  \
73  01-01-2014  29.414000   40.720425  118.800003  34.125069  110.302818   
86  01-01-2015  26.652824   35.040260  125.660004  36.613895  122.255821   
62  01-01-2016  37.147499   49.390697   89.529999  32.274353   87.052704   
53  01-01-2017  39.839500   58.934978  111.199997  38.593399  130.221344   
28  01-01-2018  58.497002  109.097107  118.930000  47.853382  117.399757   

    Starbucks    FVX   S&P500  
73  32.452744  1.613  4395.26  
86  31.235876  1.528  4766.18  
62  53.092152  1.335  2912.43  
53  50.428387  1.880  2834.40  
28  52.247074  2.948  2471.65

In [51]:
returns= data[[key for key in dict(data.dtypes) if dict(data.dtypes)[key] in ['float64','int64']]].pct_change()

In [53]:
data.describe()

Google        MSFT         CVX      Oracle         IBM   Starbucks  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    48.738647   90.786659  108.644800   42.657865  112.375547   55.860041   
std     23.111562   64.513197   14.735341   10.504181   10.627036   21.248160   
min     19.780607   23.786327   69.510002   26.397947   87.052704   23.969864   
25%     28.763032   40.457835  101.705002   35.293926  105.666763   42.438245   
50%     45.367250   63.844888  111.699997   40.736891  111.363086   51.238592   
75%     59.486375  126.578839  119.970001   48.857207  118.568972   70.164089   
max    125.316002  267.383179  130.940002   76.558250  138.578766  110.481926   

              FVX       S&P500  
count  100.000000   100.000000  
mean     1.547660  2988.392400  
std      0.675345   822.757385  
min      0.215000  1920.030000  
25%      1.211750  2228.825000  
50%      1.544500  2800.390000  
75%      1.881250  3724.697500  
max      2.987000  4766.180000

In [54]:
returns=returns[1:]

In [55]:
returns.head()

Google      MSFT       CVX    Oracle       IBM  Starbucks       FVX  \
86 -0.093873 -0.139492  0.057744  0.072932  0.108365  -0.037497 -0.052697   
62  0.393755  0.409541 -0.287522 -0.118522 -0.287946   0.699717 -0.126309   
53  0.072468  0.193240  0.242042  0.195792  0.495891  -0.050172  0.408240   
28  0.468317  0.851144  0.069514  0.239937 -0.098460   0.036065  0.568085   
31 -0.045789 -0.030428 -0.060204 -0.050498 -0.178163   0.173821 -0.034939   

      S&P500  
86  0.084391  
62 -0.388938  
53 -0.026792  
28 -0.127981  
31 -0.019517

In [56]:
returns['Intercept']=1   # useful when calculating factor models

### Estimating Historical Risk

Standard Deviation of Portfolio, Covariance Matrix makes this easy.

In [57]:
stocknames=['Google','MSFT','CVX','Oracle','IBM','Starbucks']    //these lists can be used to subset our original dataframe

In [58]:
factornames=['FVX','S&P500','Intercept']

In [59]:
stockReturns=returns[stocknames]

In [60]:
stockReturns.head()

Google      MSFT       CVX    Oracle       IBM  Starbucks
86 -0.093873 -0.139492  0.057744  0.072932  0.108365  -0.037497
62  0.393755  0.409541 -0.287522 -0.118522 -0.287946   0.699717
53  0.072468  0.193240  0.242042  0.195792  0.495891  -0.050172
28  0.468317  0.851144  0.069514  0.239937 -0.098460   0.036065
31 -0.045789 -0.030428 -0.060204 -0.050498 -0.178163   0.173821

In [61]:
factorReturns=returns[factornames]

In [62]:
factorReturns.head()

FVX    S&P500  Intercept
86 -0.052697  0.084391          1
62 -0.126309 -0.388938          1
53  0.408240 -0.026792          1
28  0.568085 -0.127981          1
31 -0.034939 -0.019517          1

Time to define an actual portfolio

In [63]:
#hence weight vectors          #equal dollar weighted portfolio

weights=np.array([1.0/len(stocknames)]*len(stocknames))         

In [64]:
weights

array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667])

 #### Variance of the portfolio can be found by multiplying the weight vector with the covariance matrix.
 
 ####              V(P)= W*Cov(Y)*Wt
 Where Y is the covariance matrix of the original stocks
 W is weight vector.

In [65]:
historicalTotalRisk= np.dot(np.dot(weights,stockReturns.cov()),weights.T)  # .cov method returns the covariance matrix of a DF, .T for transpose

In [66]:
historicalTotalRisk

0.041832163744068215

### Building Factor Models
I'll perform a Factor Analysis, we'll decompose our portfolio into 2 components: Systemic and Idiosyncratic Risks. For this, i'll build indivisual factor models for each stock in this portfolio

In [69]:
pip install statsmodels 


     ---------------------------------------- 9.2/9.2 MB 983.0 kB/s eta 0:00:00
     ------------------------------------ 233.8/233.8 kB 493.6 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [71]:
import statsmodels.api as sm

In [73]:
xData=factorReturns

In [74]:
xData.head()      #statsmodel doesn't include an intercept while performing regression, therfore the extra Intercept column

FVX    S&P500  Intercept
86 -0.052697  0.084391          1
62 -0.126309 -0.388938          1
53  0.408240 -0.026792          1
28  0.568085 -0.127981          1
31 -0.034939 -0.019517          1

In [75]:
modelCoeffs=[]

In [78]:
for oneStockName in stocknames: 
    yData= stockReturns[oneStockName]            #list of returns for each corresponding stock
    model=sm.OLS(yData,xData)                    #Returns a simple Linear Regression Model
    result=model.fit()                           
    modelCoeffRow= list(result.params)           #Extracting the result of the regression itself
    modelCoeffRow.append(np.std(result.resid,ddof=1))           # Std Devs of the residuals of the regression, ddof=1 for Bessel's Correction
    modelCoeffs.append(modelCoeffRow)                
    print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                 Google   R-squared:                       0.715
Model:                            OLS   Adj. R-squared:                  0.709
Method:                 Least Squares   F-statistic:                     120.6
Date:                Thu, 09 Feb 2023   Prob (F-statistic):           6.52e-27
Time:                        16:14:50   Log-Likelihood:                 25.201
No. Observations:                  99   AIC:                            -44.40
Df Residuals:                      96   BIC:                            -36.62
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
FVX            0.0481      0.027      1.806      0.0

In [80]:
modelCoeffs=pd.DataFrame(modelCoeffs)

In [81]:
modelCoeffs

0         1         2         3
0  0.048135 -0.956893  0.133040  0.188545
1 -0.000195 -1.138901  0.247335  0.259389
2  0.082606  0.184348 -0.009996  0.162628
3  0.036939 -0.561843  0.053375  0.173797
4  0.001739  0.158340  0.003548  0.130060
5  0.060142 -0.977639  0.114568  0.214236

In [82]:
modelCoeffs.columns= ['B_SP','B_FVX',"Alpha","ResidVol"]

In [83]:
modelCoeffs

B_SP     B_FVX     Alpha  ResidVol
0  0.048135 -0.956893  0.133040  0.188545
1 -0.000195 -1.138901  0.247335  0.259389
2  0.082606  0.184348 -0.009996  0.162628
3  0.036939 -0.561843  0.053375  0.173797
4  0.001739  0.158340  0.003548  0.130060
5  0.060142 -0.977639  0.114568  0.214236

In [85]:
modelCoeffs["Names"]=stocknames

In [86]:
modelCoeffs

B_SP     B_FVX     Alpha  ResidVol      Names
0  0.048135 -0.956893  0.133040  0.188545     Google
1 -0.000195 -1.138901  0.247335  0.259389       MSFT
2  0.082606  0.184348 -0.009996  0.162628        CVX
3  0.036939 -0.561843  0.053375  0.173797     Oracle
4  0.001739  0.158340  0.003548  0.130060        IBM
5  0.060142 -0.977639  0.114568  0.214236  Starbucks

#### We now have a nice dataframe encapsulating all the info required to calculate the systemic and idiosyncratic risk.

##### Systemic Var(P) = W* B * Cov(F) * BT * WT

B, this is the factor beta matrix.This has k rows and 2 columns, these correspond to the betas of each of our stocks on the FVX and the S&P repectively.

y = A + B₁F₁ + B₂F2

Cov(F) = [ Var(F₁) Cov(F1,F2) ]
         [ Cov(F1,F2) Var(F2) ]                                 
             
Factor Covariance matrix, 2by2 matric bc we have 2 factors.     

In [88]:
factorCov = factorReturns [["FVX", "S&P500"]].cov()

In [89]:
factorCov

FVX    S&P500
FVX     0.953295  0.225553
S&P500  0.225553  0.117799

In [94]:
 #Let's first calculate the matrix product of the three inner terms, i.e. B * Cov(F) * BT,   This will give us a reconstructed covariance matrix for the stocks in the portfolio
 #This is a k by k matrix.

reconstructedCov = np.dot(np.dot(modelCoeffs[["B_FVX", "B_SP"]], factorCov), modelCoeffs[["B_FVX", "B_SP"]].T)
    

In [95]:
reconstructedCov

array([[ 0.8523745 ,  1.02658357, -0.18352116,  0.49865075, -0.14308393,
         0.86855039],
       [ 1.02658357,  1.23661569, -0.22137789,  0.60053253, -0.17236436,
         1.04602391],
       [-0.18352116, -0.22137789,  0.04007018, -0.10730979,  0.03086563,
        -0.18693746],
       [ 0.49865075,  0.60053253, -0.10730979,  0.29172248, -0.0837005 ,
         0.50812014],
       [-0.14308393, -0.17236436,  0.03086563, -0.0837005 ,  0.02402501,
        -0.14579227],
       [ 0.86855039,  1.04602391, -0.18693746,  0.50812014, -0.14579227,
         0.88504119]])

In [102]:
#To calculate systemic risk, we simply pre-multiply reconstructed matrix by the weights and post-multiply it by the transpose of the weights
systemicRisk = np.dot(np.dot(weights, reconstructedCov), weights.T)

In [100]:
#P = W₁Y1+ W2Y2+W3Y3... + WkYk
#IdiosyncraticVar(P) = Σ w^2 Var(e)

#This is the product of squares of the weights multiplied by the volatility of the residuals. The residuals are obtained from each individual regression model that we built.

idiosyncraticRisk = sum(modelCoeffs["ResidVol"]*modelCoeffs["ResidVol"]*weights*weights)



In [101]:
idiosyncraticRisk

0.006174940727671326

In [103]:
systemicRisk

0.2777868941199702

In [104]:
factorModelTotalRisk = systemicRisk + idiosyncraticRisk


In [105]:
factorModelTotalRisk

0.28396183484764154

### Scenario Based Stress Testing
This step is imp. because it leads to scenarios which lead to extreme combinations, we do this by taking the minimum factor returns on the FVX and the S&P, the corresponding maximum returns, and then generating scenarios with a certain step change.
That step change corresponds to 5% on the FVX and 2% on the S&P. This might give some scenarios that might be too extreme



In [109]:
fvxScenarios = np.arange(min(returns["FVX"]),max(returns["FVX"]),0.05)


In [110]:
fvxScenarios   #FVX scenarios that correspond to different movements, ranging from a fall of 88% to an increase of 481%

array([-0.88340564, -0.83340564, -0.78340564, -0.73340564, -0.68340564,
       -0.63340564, -0.58340564, -0.53340564, -0.48340564, -0.43340564,
       -0.38340564, -0.33340564, -0.28340564, -0.23340564, -0.18340564,
       -0.13340564, -0.08340564, -0.03340564,  0.01659436,  0.06659436,
        0.11659436,  0.16659436,  0.21659436,  0.26659436,  0.31659436,
        0.36659436,  0.41659436,  0.46659436,  0.51659436,  0.56659436,
        0.61659436,  0.66659436,  0.71659436,  0.76659436,  0.81659436,
        0.86659436,  0.91659436,  0.96659436,  1.01659436,  1.06659436,
        1.11659436,  1.16659436,  1.21659436,  1.26659436,  1.31659436,
        1.36659436,  1.41659436,  1.46659436,  1.51659436,  1.56659436,
        1.61659436,  1.66659436,  1.71659436,  1.76659436,  1.81659436,
        1.86659436,  1.91659436,  1.96659436,  2.01659436,  2.06659436,
        2.11659436,  2.16659436,  2.21659436,  2.26659436,  2.31659436,
        2.36659436,  2.41659436,  2.46659436,  2.51659436,  2.56

In [113]:
 spScenarios =np.arange(min(returns["S&P500" ]),max(returns["S&P500"]),0.02)

In [114]:
spScenarios

array([-0.4090934, -0.3890934, -0.3690934, -0.3490934, -0.3290934,
       -0.3090934, -0.2890934, -0.2690934, -0.2490934, -0.2290934,
       -0.2090934, -0.1890934, -0.1690934, -0.1490934, -0.1290934,
       -0.1090934, -0.0890934, -0.0690934, -0.0490934, -0.0290934,
       -0.0090934,  0.0109066,  0.0309066,  0.0509066,  0.0709066,
        0.0909066,  0.1109066,  0.1309066,  0.1509066,  0.1709066,
        0.1909066,  0.2109066,  0.2309066,  0.2509066,  0.2709066,
        0.2909066,  0.3109066,  0.3309066,  0.3509066,  0.3709066,
        0.3909066,  0.4109066,  0.4309066,  0.4509066,  0.4709066,
        0.4909066,  0.5109066,  0.5309066,  0.5509066,  0.5709066,
        0.5909066,  0.6109066,  0.6309066,  0.6509066,  0.6709066,
        0.6909066,  0.7109066,  0.7309066,  0.7509066,  0.7709066,
        0.7909066,  0.8109066,  0.8309066,  0.8509066,  0.8709066,
        0.8909066,  0.9109066,  0.9309066,  0.9509066,  0.9709066,
        0.9909066,  1.0109066,  1.0309066,  1.0509066,  1.0709

In [137]:
scenarios=[]

In [140]:
for oneFVXValue in fvxScenarios:     #This for loop iterates over all of the values in the FVX and the S&P scenarios,
  for oneSPValue in spScenarios:
    oneScenario = [oneFVXValue, oneSPValue]  #And then for each simulated value in the FVX and the S&P, we calculate the stock return, using the factor model we had previously set
    for oneStockName in stocknames:
        alpha = float(modelCoeffs[modelCoeffs["Names"]==oneStockName ][ "Alpha" ])
        beta_sp = float(modelCoeffs[modelCoeffs["Names"]==oneStockName]["B_SP"])
        beta_fvx = float(modelCoeffs[modelCoeffs["Names"] == oneStockName]["B_FVX"])
        oneStockPredictedReturn = alpha + beta_sp * oneSPValue + beta_fvx * oneFVXValue
        oneScenario.append(oneStockPredictedReturn)
    scenarios.append(oneScenario)


In [141]:
scenarios = pd.DataFrame(scenarios)

In [142]:
scenarios

0         1         2         3         4         5         6  \
0     -0.883406 -0.409093  0.958673  1.253526 -0.206643  0.534599 -0.137041   
1     -0.883406 -0.389093  0.959635  1.253522 -0.204991  0.535338 -0.137006   
2     -0.883406 -0.369093  0.960598  1.253518 -0.203339  0.536076 -0.136972   
3     -0.883406 -0.349093  0.961561  1.253515 -0.201687  0.536815 -0.136937   
4     -0.883406 -0.329093  0.962523  1.253511 -0.200035  0.537554 -0.136902   
...         ...       ...       ...       ...       ...       ...       ...   
19775  4.816594  1.210907 -4.417639 -5.238527  0.977960 -2.608063  0.768311   
19776  4.816594  1.230907 -4.416677 -5.238531  0.979612 -2.607324  0.768346   
19777  4.816594  1.250907 -4.415714 -5.238535  0.981264 -2.606585  0.768381   
19778  4.816594  1.270907 -4.414751 -5.238538  0.982916 -2.605846  0.768415   
19779  4.816594  1.290907 -4.413789 -5.238542  0.984569 -2.605108  0.768450   

              7  
0      0.953616  
1      0.954819  
2      0.956022  
3      0.957225  
4      0.958428  
...         ...  
19775 -4.521496  
19776 -4.520294  
19777 -4.519091  
19778 -4.517888  
19779 -4.516685  

[19780 rows x 8 columns]

In [143]:
scenarios.columns= ["FVX","S&P500",'Google','MSFT','CVX','Oracle','IBM','Starbucks']

In [144]:
scenarios.columns

Index(['FVX', 'S&P500', 'Google', 'MSFT', 'CVX', 'Oracle', 'IBM', 'Starbucks'], dtype='object')

In [146]:
scenariosCov= scenarios[stocknames].cov()     #Calculating the covariance of a subset off this dataFrame, this can be plugged into the calculation of simulated or scenario based portfolio.

In [147]:
scenarios.cov()

FVX        S&P500    Google      MSFT       CVX    Oracle  \
FVX        2.755139e+00 -1.796205e-19 -2.636374 -3.137832  0.507903 -1.547955   
S&P500    -1.796205e-19  2.465125e-01  0.011866 -0.000048  0.020363  0.009106   
Google    -2.636374e+00  1.186595e-02  2.523299  3.002567 -0.485029  1.481666   
MSFT      -3.137832e+00 -4.808130e-05  3.002567  3.573680 -0.578456  1.762966   
CVX        5.079033e-01  2.036344e-02 -0.485029 -0.578456  0.095313 -0.284609   
Oracle    -1.547955e+00  9.105956e-03  1.481666  1.762966 -0.284609  0.870043   
IBM        4.362474e-01  4.286608e-04 -0.417422 -0.496843  0.080457 -0.245087   
Starbucks -2.693532e+00  1.482567e-02  2.578136  3.067664 -0.495321  1.513888   

                IBM  Starbucks  
FVX        0.436247  -2.693532  
S&P500     0.000429   0.014826  
Google    -0.417422   2.578136  
MSFT      -0.496843   3.067664  
CVX        0.080457  -0.495321  
Oracle    -0.245087   1.513888  
IBM        0.069076  -0.426467  
Starbucks -0.426467   2.634193

In [149]:
scenarioTotalRisk= np.dot(np.dot(weights,scenariosCov),weights.T)

In [150]:
scenarioTotalRisk

0.8300506834574495

### Value-At-Risk 
Quantifying the worst case approaches using VAR
How much can we afford to lose

VAR(given alpha) = P * Z(alpha) * sigma

where P: $ invested
sigma:   square root of variance returned(from historical, factor or scenario analysis)
Z(alpha):Number of standard deviations away from mean where the probability = 1-alpha

Multi-period VAR: P * Z(alpha) * sigma * h^(1/2)      
where h: no. of trading periods

In [158]:
from scipy.stats import norm
import math

In [165]:
def calculateVaR(risk,confLevel,principal=1, numMonths=1):                  # risk is variance of portfolio, confLevel: prob of loss
    vol= math.sqrt(risk)                                                    # calculating volatility
    return abs(principal*norm.ppf(1-confLevel,0,1)*vol*math.sqrt(numMonths))    #norm.ppf used for calculating the mean score Z

In [166]:
calculateVaR(scenarioTotalRisk,0.99)        # Loss probability = 0.99      #The probability that we will experience a loss of 211% or greater is 1% 

2.1194684879224366

In [168]:
calculateVaR(historicalTotalRisk,0.99) 

0.475805899506801

In [169]:
calculateVaR(factorModelTotalRisk,0.99) 

1.2396658713717674